# Generated by Django 5.2.4 on 2025-08-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfaculty',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='customfaculty',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customfaculty',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfaculty',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
