# Generated by Django 5.2.4 on 2025-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_years', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'academic_year',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
