# Generated by Django 5.2.4 on 2025-08-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_academic_year_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_year',
            name='additional_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='academic_year',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
