# Generated by Django 5.2.4 on 2025-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_academic_year_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfaculty',
            name='user_type',
            field=models.CharField(default='faculty', max_length=50),
        ),
        migrations.AddField(
            model_name='customstudent',
            name='user_type',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
