# Generated by Django 5.2.4 on 2025-08-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customfaculty_user_type_customstudent_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='unit_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
