# Generated by Django 5.2.4 on 2025-08-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_description_course_resources_course_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title_code',
            field=models.CharField(max_length=20, verbose_name='Course Code'),
        ),
    ]
