# Generated by Django 5.2.4 on 2025-08-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_course_title_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
