# Generated by Django 5.2.4 on 2025-08-05 11:50

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pdf', models.FileField(null=True, upload_to='pdf_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'db_table': 'upload_units',
            },
        ),
    ]
