# Generated by Django 5.2.4 on 2025-08-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_upload_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_units',
            old_name='course',
            new_name='course_id',
        ),
    ]
