# Generated by Django 5.2.4 on 2025-08-06 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_course_upload_units_course_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='previous_question_papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='previous_question_papers', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('academic_year', models.CharField(max_length=20, null=True)),
                ('semmester', models.CharField(max_length=20, null=True)),
                ('question_paper_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'previous_question_papers',
            },
        ),
    ]
