# Generated by Django 5.2.4 on 2025-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_previous_question_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_event_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, null=True)),
                ('event_date', models.DateField(null=True)),
                ('event_time', models.TimeField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('descritpion', models.TextField(null=True)),
                ('organizer_name', models.CharField(max_length=50, null=True)),
                ('contact_mail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'college_event_model',
            },
        ),
    ]
