# Generated by Django 5.2.4 on 2025-10-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_college_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
