from django.urls import path
from . views import *
urlpatterns = [
    path('', index, name='index'),
    path('adminDashboard/', adminDashboard, name='adminDashboard'),
    path('admin_login/', admin_login, name='admin_login'),
    path('student_reg/', student_reg, name='student_reg'),
    path('student_log/', student_log, name='student_log'),
    path('faculty_log/', faculty_log, name='faculty_log'),
    path('logout_user/', logout_user, name='logout_user'),
    path('add_faculty/', add_faculty, name='add_faculty'),
    path('dashboard/', dashboard, name='dashboard'),
    path('verify_student_otp/', verify_student_otp, name='verify_student_otp'),
    path('view_profile_student/', view_profile_student, name='view_profile_student'),
    path('add_syllabus/', add_syllabus, name='add_syllabus'),
    path('add_academic_year/', add_academic_year, name='add_academic_year'),
    path('view_course/', view_course, name='view_course'),
    path('remove_units/<int:id>/', remove_units, name='remove_units'),
    path('add_unit_content/<int:id>/', add_unit_content, name='add_unit_content'),
    path('preview_unit/<int:unit_id>/', preview_unit, name='preview_unit'),
    path('add_question_papers/', add_question_papers, name='add_question_papers'),
    path('add_question_papers_1/<str:title>/', add_question_papers_1, name='add_question_papers_1'),
    path('view_students/', view_students, name='view_students'),
    path('view_course_student/', view_course_student, name='view_course_student'),
    path('view_syllabus_student/<int:user_id>/<str:subject>/',view_syllabus_student, name='view_syllabus_student'),
    path('preview_unit_student/<str:unit_id>/',preview_unit_student,name='preview_unit_student'),
    path('view_all_students/', view_all_students, name='view_all_students'),
    path('view_all_faculty/', view_all_faculty, name='view_all_faculty'),
    path('add_events/', add_events, name='add_events'),
    path('view_events/', view_events, name='view_events'),
    path('remove_event/<int:id>/', remove_event, name='remove_event'),
    path('forgot_pass/', forgot_pass, name='forgot_pass'),
    path('reset_pass/', reset_pass, name='reset_pass'),
    path('setPass/', setPass, name='setPass'),
    path('delete_student/<int:id>/', delete_student, name='delete_student'),
    path('delete_faculty/<int:id>/', delete_faculty, name='delete_faculty'),
    path('delete_academic_year/<int:id>/', delete_academic_year, name='delete_academic_year')
]